package com.example.housespot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import java.util.Arrays;
import java.util.List;

import static com.example.housespot.MachineLearningController.*;

@Controller
public class MachineLearningWebController {

    private final MachineLearningService tfServingClient;

    @Autowired
    public MachineLearningWebController(MachineLearningService tfServingClient) {
        this.tfServingClient = tfServingClient;
    }

    private final List<String> districtsAndCities = Arrays.asList("Bekasi, Babelan",
            "Bekasi, Pondokmelati",
            "Bekasi, Bekasi Utara",
            "Bekasi, Cikarang Pusat",
            "Bekasi, Mustikajaya",
            "Bekasi, Rawalumbu",
            "Bekasi, Setu",
            "Bekasi, Bekasi Barat",
            "Bekasi, Jatiasih",
            "Bekasi, Bekasi Timur",
            "Bekasi, Bekasi Selatan",
            "Bekasi, Cibitung",
            "Bekasi, Medan Satria",
            "Bekasi, Kedungwaringin",
            "Bekasi, Jatibening",
            "Bekasi, Pondokgede",
            "Bekasi, Tambun Utara",
            "Bekasi, Bantargebang",
            "Bekasi, Cikarang Barat",
            "Bekasi, Serang Baru",
            "Bekasi, Tarumajaya",
            "Bekasi, Jawa Barat",
            "Bekasi, Jatisampurna",
            "Bekasi, Cibarusah",
            "Bekasi, Tambun Selatan",
            "Bekasi, Cikarang Selatan",
            "Bekasi, Cikarang Utara",
            "Bekasi, Sukawangi",
            "Bekasi, Cikarang Timur",
            "Bekasi, Sukatani",
            "Bekasi, Karangbahagia",
            "Bogor, Parung Panjang",
            "Bogor, Dramaga",
            "Bogor, Gunung Putri",
            "Bogor, Babakan Madang",
            "Bogor, Bogor Barat",
            "Bogor, Rumpin",
            "Bogor, Bogor Timur",
            "Bogor, Tajur Halang",
            "Bogor, Ciomas",
            "Bogor, Cibinong",
            "Bogor, Bojong Gede",
            "Bogor, Jonggol",
            "Bogor, Bogor Utara",
            "Bogor, Gunung Sindur",
            "Bogor, Ciampea",
            "Bogor, Ciawi",
            "Bogor, Tanah Sereal",
            "Bogor, Cisarua",
            "Bogor, Kemang",
            "Bogor, Ciseeng",
            "Bogor, Leuwiliang",
            "Bogor, Bogor Selatan",
            "Bogor, Sukaraja",
            "Bogor, Tenjo",
            "Bogor, Cijeruk",
            "Bogor, Cileungsi",
            "Bogor, Bogor Tengah",
            "Bogor, Pamijahan",
            "Bogor, Cibungbulang",
            "Bogor, Ranca Bungur",
            "Bogor, Citeureup",
            "Bogor, Parung",
            "Bogor, Caringin",
            "Bogor, Leuwisadeng",
            "Bogor, Legenda Wisata",
            "Bogor, Tamansari",
            "Bogor, Jasinga",
            "Bogor, Kelapa Nunggal",
            "Bogor, Cariu",
            "Bogor, Megamendung",
            "Bogor, Bali Resort Bogor",
            "Tangerang, Panongan",
            "Tangerang, Karang Tengah",
            "Tangerang, Cisauk",
            "Tangerang, Karawaci",
            "Tangerang, L'Agricola",
            "Tangerang, Tangerang",
            "Tangerang, Periuk",
            "Tangerang, Benda",
            "Tangerang, Cikupa",
            "Tangerang, Curug",
            "Tangerang, Kelapa Dua",
            "Tangerang, Pagedangan",
            "Tangerang, Cipondoh",
            "Tangerang, Pinang",
            "Tangerang, Ciledug",
            "Tangerang, Larangan",
            "Tangerang, Legok",
            "Tangerang, Teluknaga",
            "Tangerang, Sepatan",
            "Tangerang, Cibodas",
            "Tangerang, Rajeg",
            "Tangerang, Sindang Jaya",
            "Tangerang, Pondok Hijau Golf",
            "Tangerang, Sepatan Timur",
            "Tangerang, Bsd City",
            "Tangerang, Mauk",
            "Tangerang, Balaraja",
            "Tangerang, Cisoka",
            "Tangerang, Pasarkemis",
            "Tangerang, Tigaraksa",
            "Tangerang, Jambe",
            "Tangerang, Jati Uwung",
            "Tangerang, Batuceper",
            "Tangerang, Taman Parahyangan",
            "Tangerang, Daan Mogot Arcadia",
            "Tangerang, Pakuhaji",
            "Tangerang, Sukadiri",
            "Tangerang, Neglasari",
            "Tangerang, Kosambi",
            "Tangerang, Cikupa Citra Raya",
            "Tangerang, Solear",
            "Tangerang, Jayanti",
            "Tangerang, Kresek",
            "Depok, Cilodong",
            "Depok, Cipayung",
            "Depok, Sawangan",
            "Depok, Sukma Jaya",
            "Depok, Beji",
            "Depok, Cinere",
            "Depok, Tapos",
            "Depok, Pancoran Mas",
            "Depok, Cimanggis",
            "Depok, Limo",
            "Depok, Bojongsari",
            "Depok, Cinangka",
            "Depok, Grand Depok City",
            "Bogor, Bojonggede",
            "Bogor, Tajurhalang",
            "Bogor, Klapanunggal",
            "Jakarta Timur, Jatinegara",
            "Jakarta Timur, Ciracas",
            "Jakarta Timur, Cakung",
            "Jakarta Selatan, Pasar Minggu",
            "Jakarta Pusat, Cempaka Putih",
            "Jakarta Utara, Kelapa Gading",
            "Jakarta Barat, Palmerah",
            "Jakarta Utara, Penjaringan",
            "Jakarta Barat, Grogol Petamburan",
            "Jakarta Barat, Cengkareng",
            "Jakarta Selatan, Pesanggrahan",
            "Jakarta Selatan, Mampang Prapatan",
            "Jakarta Selatan, Kebayoran Baru",
            "Jakarta Selatan, Cilandak",
            "Jakarta Barat, Kali Deres",
            "Jakarta Timur, Duren Sawit",
            "Jakarta Timur, Cipayung",
            "Jakarta Selatan, Setia Budi",
            "Jakarta Selatan, Kebayoran Lama",
            "Jakarta Barat, Kembangan",
            "Jakarta Selatan, Jagakarsa",
            "Jakarta Barat, Kebon Jeruk",
            "Jakarta Timur, Pasar Rebo",
            "Jakarta Utara, Pademangan",
            "Jakarta Timur, Pulo Gadung",
            "Jakarta Utara, Cilincing",
            "Jakarta Selatan, Pancoran",
            "Jakarta Timur, Matraman",
            "Jakarta Timur, Kramat Jati",
            "Jakarta Selatan, Tebet",
            "Jakarta Pusat, Gambir",
            "Jakarta Pusat, Tanah Abang",
            "Jakarta Timur, Makasar",
            "Jakarta Pusat, Senen",
            "Jakarta Utara, Tanjung Priok",
            "Jakarta Pusat, Johar Baru",
            "Jakarta Pusat, Menteng",
            "Jakarta Pusat, Kemayoran",
            "Jakarta Barat, Tambora",
            "Jakarta Barat, Taman Sari",
            "Jakarta Pusat, Sawah Besar",
            "Jakarta Utara, Koja",
            "Jakarta Barat, Citra Garden 2 Extension",
            "Jakarta Utara, Pantai Indah Kapuk",
            "Jakarta Barat, Puri Indah",
            "Jakarta Barat, Permata Buana",
            "Jakarta Utara, Sunter",
            "Jakarta Selatan, Cipete",
            "Jakarta Selatan, Lebak Bulus",
            "Jakarta Utara, Pantai Indah Kapuk 2",
            "Jakarta Barat, Taman Ratu",
            "Jakarta Barat, Metland Puri",
            "Jakarta Utara, Pluit",
            "Jakarta Barat, Tanjung Duren",
            "Jakarta Selatan, Pondok Indah",
            "Jakarta Barat, Kav Dki",
            "Jakarta Selatan, Kemang",
            "Jakarta Selatan, Setiabudi",
            "Jakarta Barat, Duri Kepa",
            "Jakarta Barat, Duri Kosambi",
            "Jakarta Barat, Green Lake City",
            "Jakarta Barat, Daan Mogot",
            "Jakarta Barat, Intercon",
            "Jakarta Timur, Cibubur",
            "Jakarta Barat, Taman Meruya",
            "Jakarta Pusat, Percetakan Negara",
            "Jakarta Timur, Cipinang",
            "Jakarta Selatan, Kebagusan",
            "Jakarta Utara, Ancol",
            "Jakarta Selatan, Pejaten",
            "Jakarta Barat, Citra Garden",
            "Jakarta Barat, Puri Mansion",
            "Jakarta Barat, Tomang",
            "Jakarta Timur, Jatiwaringin",
            "Jakarta Barat, Meruya",
            "Jakarta Utara, Golf Island",
            "Jakarta Selatan, Cirendeu",
            "Jakarta Barat, Kemanggisan",
            "Jakarta Timur, Condet",
            "Jakarta Barat, Joglo",
            "Jakarta Barat, Kalideres",
            "Jakarta Barat, Semanan",
            "Jakarta Selatan, Permata Hijau",
            "Jakarta Barat, Jelambar",
            "Jakarta Selatan, Kalibata",
            "Jakarta Utara, Muara Karang",
            "Jakarta Barat, Green Ville",
            "Jakarta Timur, Rawamangun",
            "Jakarta Barat, Puri Media",
            "Jakarta Selatan, Kuningan",
            "Jakarta Barat, Tamansari",
            "Jakarta Selatan, Patra Kuningan",
            "Jakarta Selatan, Radio Dalam",
            "Jakarta Selatan, Warung Buncit",
            "Jakarta Barat, Green Garden",
            "Jakarta Utara, Pantai Mutiara",
            "Jakarta Timur, Pisangan Lama",
            "Jakarta Selatan, Sudirman",
            "Jakarta Selatan, Mega Kuningan",
            "Jakarta Selatan, Pondok Labu",
            "Jakarta Selatan, Bintaro",
            "Jakarta Selatan, Guntur",
            "Jakarta Pusat, Cempaka Mas",
            "Jakarta Timur, Pondok Kelapa",
            "Jakarta Utara, Taman Grisenda",
            "Jakarta Barat, Kedoya",
            "Jakarta Selatan, Ampera",
            "Jakarta Barat, Sunrise Garden",
            "Jakarta Timur, Citra Grand",
            "Jakarta Timur, Taman Mini",
            "Jakarta Timur, Kayu Putih",
            "Jakarta Selatan, Pakubuwono",
            "Jakarta Timur, Utan Kayu",
            "Jakarta Selatan, Gandaria",
            "Jakarta Barat, Duta Garden",
            "Jakarta Pusat, Gajah Mada",
            "Jakarta Selatan, Jati Padang",
            "Jakarta Pusat, Pasar Baru",
            "Jakarta Barat, Taman Palem",
            "Jakarta Timur, Raffles Hills",
            "Jakarta Timur, Pulomas",
            "Jakarta Selatan, Fatmawati",
            "Jakarta Barat, Tanjung Duren Selatan",
            "Jakarta Selatan, Cipedak",
            "Jakarta Barat, Jembatan Dua",
            "Jakarta Barat, Grogol",
            "Jakarta Timur, Pinang Ranti",
            "Jakarta Pusat, Petojo",
            "Jakarta Timur, Cilangkap",
            "Jakarta Barat, Jembatan Lima",
            "Jakarta Pusat, Cideng",
            "Jakarta Selatan, Ciganjur",
            "Jakarta Selatan, Duren Tiga",
            "Jakarta Pusat, Karang Anyar",
            "Jakarta Selatan, Mampang",
            "Jakarta Selatan, Sektor 3 - Bintaro",
            "Jakarta Pusat, Harmoni",
            "Jakarta Selatan, Simprug",
            "Jakarta Timur, Kota Wisata",
            "Jakarta Timur, Bambu Apus",
            "Jakarta Barat, Villa Meruya",
            "Jakarta Utara, Pegangsaan",
            "Jakarta Selatan, Tb Simatupang",
            "Jakarta Selatan, Blok M",
            "Jakarta Timur, Cawang",
            "Jakarta Selatan, Veteran",
            "Jakarta Selatan, Cinere",
            "Jakarta Selatan, Menteng Dalam",
            "Jakarta Pusat, Salemba",
            "Jakarta Selatan, Lenteng Agung",
            "Jakarta Barat, Bojong Indah",
            "Jakarta Selatan, Ulujami",
            "Jakarta Barat, Mangga Besar",
            "Jakarta Timur, Cipinang Melayu",
            "Jakarta Selatan, Prapanca",
            "Jakarta Timur, Cijantung",
            "Jakarta Timur, Legenda Wisata",
            "Jakarta Selatan, Bangka",
            "Jakarta Selatan, Tanjung Barat",
            "Jakarta Timur, Kalisari",
            "Jakarta Barat, Alfa Indah",
            "Jakarta Barat, Angke",
            "Jakarta Pusat, Pejompongan",
            "Jakarta Pusat, Hasyim Ashari",
            "Jakarta Pusat, Gunung Sahari",
            "Jakarta Selatan, Sektor 2 - Bintaro",
            "Jakarta Selatan, Tanah Kusir",
            "Jakarta Barat, Slipi",
            "Jakarta Pusat, Kebon Kacang",
            "Jakarta Timur, Pondok Gede",
            "Jakarta Selatan, Scbd",
            "Jakarta Selatan, Bukit Duri",
            "Jakarta Utara, Teluk Gong",
            "Jakarta Timur, Buaran",
            "Jakarta Timur, Klender",
            "Jakarta Selatan, Panglima Polim",
            "Jakarta Pusat, Bendungan Hilir",
            "Jakarta Timur, Pondok Bambu",
            "Jakarta Timur, Pulogebang",
            "Jakarta Barat, Kedoya Baru",
            "Jakarta Selatan, Ragunan",
            "Jakarta Selatan, Petukangan",
            "Jakarta Barat, Taman Surya",
            "Jakarta Barat, Tawakal",
            "Jakarta Selatan, Senayan",
            "Jakarta Barat, Tanjung Duren Utara",
            "Jakarta Barat, Cengkareng Barat",
            "Jakarta Selatan, Blok S",
            "Jakarta Timur, Kayu Jati",
            "Jakarta Pusat, Bungur",
            "Jakarta Timur, Pondok Ranggon",
            "Jakarta Selatan, Patal Senayan",
            "Jakarta Barat, Kelapa Dua",
            "Jakarta Selatan, Cikoko",
            "Jakarta Pusat, Menteng Atas",
            "Jakarta Selatan, Senopati",
            "Jakarta Barat, Green Mansion",
            "Jakarta Selatan, Cipulir",
            "Jakarta Pusat, Sumur Batu",
            "Jakarta Selatan, Pondok Pinang",
            "Jakarta Selatan, Graha Bintaro"
    );

    @GetMapping("/")
    public String showForm(Model model) {
        model.addAttribute("attributeFE", new AttributeFE());
        model.addAttribute("districtsAndCities", districtsAndCities);
        return "predict-form";
    }

    @PostMapping("/")
    public String predict(@ModelAttribute AttributeFE attributeFE, Model model) throws Exception {


        System.out.println(attributeFE.getDistrictAndCity());

        String[] parts = attributeFE.getDistrictAndCity().split(",");

        String city = parts[0].trim();
        String district = parts[1].trim();

        Attribute attribute = new Attribute(district,city, attributeFE.getLatitude(), attributeFE.getLongitude(), attributeFE.getLandSize(), attributeFE.getBuildingSize(), attributeFE.getFloors(), attributeFE.getBedrooms(), attributeFE.getBathrooms(), attributeFE.getCarportGarage());

        int encodedCity = MachineLearningController.CityEncoder.encodeCity(attribute.getCity());

        int encodedDistrict = MachineLearningController.DistrictEncoder.encodeDistrict(attribute.getDistrict());

        List<Float> listFeaturesEncodedScaled = MachineLearningController.MinMaxScaler.scale(attribute, encodedDistrict, encodedCity);

        String body = createRequestBody(listFeaturesEncodedScaled);

        String response = tfServingClient.predict(body);

        float predictionFloat = getPredictionFromJson(response);

        int roundedPrediction = rounder(predictionFloat);

        String result = MachineLearningController.CategoryEncoder.decodeCategory(roundedPrediction);

        model.addAttribute("result", result);

        return "predict-result";

    }

}
